name: Context testing
# on: push
on:
  workflow_dispatch:
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Get repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Use repo name in Vite build
        run: |
          # Access the environment variable here, for example:
          echo "Building $REPO_NAME with Vite"
          # Your Vite build commands here using $REPO_NAME

      - name: Check GitHub Pages deployment
        run: |
          if [ "$GITHUB_REPOSITORY" == "yourusername/yourrepo" ]; then
            echo "Deploying to GitHub Pages"
            # Your GitHub Pages deployment steps here
          else
            echo "Deploying to another hosting service"
            # Your deployment steps for another service here
          fi
